blank_issues_enabled: false
contact_links:
  - name: Have questions
    url: https://github.com/ververica/ForSt/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: New Ideas
    url: https://github.com/ververica/ForSt/discussions/categories/ideas
    about: Please suggest your new ideas here.